services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.letsresolver.acme.email=tuemail@dominio.com"
      - "--certificatesresolvers.letsresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - nba-vps
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nba.rule=Host(`nba-scoreboard.duckdns.org`)"
      - "traefik.http.routers.nba.entrypoints=websecure"
      - "traefik.http.routers.nba.tls.certresolver=letsresolver"
      - "traefik.http.routers.nba.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    environment:
      CONNECTION_STRING: "Server=db;Database=${MSSQL_DB};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - nba-vps

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_TCP_PORT=1433

    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - nba-vps

volumes:
  sql_data:

networks:
  nba-vps:
    driver: bridge