services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${front_port}:80"
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=nba-scoreboard.duckdns.org
      - LETSENCRYPT_HOST=nba-scoreboard.duckdns.org
      - LETSENCRYPT_EMAIL=tu-email@dominio.com
      - HTTPS_METHOD=redirect
    restart: always
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    environment:
      CONNECTION_STRING: "Server=db;Database=${MSSQL_DB};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_TCP_PORT=1433

    ports:
      - "1434:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: